server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///leyou?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 127.0.0.1
    username: leyou137
    password: leyou
    virtual-host: /leyou137
    publisher-confirms: true
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 80000ms
        multiplier: 2
mybatis-plus:
  type-aliases-package: com.leyou.item.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/*.xml

logging:
  level:
    com.leyou: debug

ly:
  jwt:
    pubKeyPath: D:\Develop\rsa-key\rsa-key.pub # 公钥地址
    cookie:
      cookieName: LY_TOKEN # cookie名称
    app:
      serviceName: item-service
      secret: item-service